sudo: required
os:
  - linux
  - osx

language: go
go:
 - tip

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    # - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch


before_install:
 - source .travis/setenv_lua.sh
 - luarocks install --server=http://luarocks.org/dev gleam-lua

install:
 - go get ./...
 # - go get $(go list ./... | grep -v word_count_in_go)

script:
 # - go test -race ./...
 - ./go.test.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
